### ISSUE TITLE
CentOS compatibility

### ISSUE THREAD

**Issue by xinhaikang** [nkadel/samba-4.9.x-srpm#2]
This is actually not an issue but a record of communication with Nico.

Original question:
> I was looking for the way to build Samba 4.8.x packages for CentOS 7.x and
> found your github repository of samba-4.8.x-srpm. With some work, now I can
> successfully build  the RPM package on CentOS 7.5. Great thanks to your awesome work!
>
> However in the readme.md I noticed you mentioned "...  Samba 4.x
> compatibilities are no longer with RHEL or CentOS, due to gnutls and other
> updates". I am wondering if you can give me some more detail information
> about this warning? and it would be great if you can show me the direction
> as how to fix it.
>

Answer from Nico:

Next time, add this as an issue on the github repo for others, please?

That was a ways back, and it may be out of date. gnutls on CentOS 6 is
a noticeably older version, and the one on CentOS 7 may be recent
enough for samba-4.8.x. samba-4.9.x, which is in development, is
reliant on Python 3, which is not built into CentOS 7 in any default
location.

**Comment by wiza** [comment]
Could you share your work? Lots of interested people interested of getting time machine capable samba for CentOS 7.

**Comment by nkadel** [comment]
I keep my work posted to github. What's there is what I've got.

I'd been working lately on 4.9, which has gotten painful to backport to CentOS 7. My last 4.8 tag here: https://github.com/nkadel/samba-4.8.x-srpm/tree/v4.8.3-0

**Comment by nkadel** [comment]
And.... you asked nicely. I built a tag, https://github.com/nkadel/samba-4.8.x-srpm/tree/v4.8.5-0 . 4.8.5 can't use the latest ldb library, so I had  to provide an older libldb package to make it work.  It doesn't build properly on Fedora 28, but that hardly seems necessary now with 4.9.1 available and mostly building for that OS

**Comment by rippiedoos** [comment]
The tag v4.8.5-0 doesn't build on OracleLinux 7(.5), I guess it doesn't build on CentOS en RHEL 7 either. Some of the problems are the requirements for python2-packages, there still named python. I've also renamed the python2-samba-package back to python-samba, as there could be some mix up if you already installed samba 4.7 and are upgrading with these pacakges. 

Also I've rebuilt the talloc-package with the updated version 2.1.14 (latest available) as Samba 4.8 needs 2.1.11. That required some other updating as well, so I've rebuilt the other dependant packages too:

 - ldb 1.3.6
 - tdb 1.3.16
 - talloc 2.1.14
 - tevent 0.9.37

I'll create a pull-request for this tag to update it, to include the updated spec-files for the rest of the RPM's and post it after I've upgraded and installed my system with this. Ah, and important for us Apple TimeMachine users, I've included a patch for Samba Bug 13441 - vfs_fruit: delete 0 byte size streams if AAPL is enabled.

**Comment by rippiedoos** [comment]
I don't know how to create a pull-request for a tag, but I created a separate branch for 4.8.5 and merged my commits into that one. Mine build fine on Oracle Linux 7.5. Maybe I need to test this on CentOS 7 as well, didn't have the time yet.

**Comment by rippiedoos** [comment]
Off course, just after spending some hours on recompiling things to 4.8.5, I read that RedHat will be doing a rebase to 4.8.3 in RedHat 7.6. So just wait for CentOS/RedHat/OracleLinux/ScientificLinux 7.6 and you have Samba 4.8.3.

https://bugzilla.redhat.com/show_bug.cgi?id=1558560

**Comment by nkadel** [comment]
Ahh I'd not done a complete set of tags and push tags. Go to the samba4repo, pull and checkout the v4.8.5 tag, make sure all submodules are set to match.

**Comment by rippiedoos** [comment]
No, I didn’t. I just used the SPEC-file to rebuild the RPMs. The goal was to be as much backwards compatible with the stock Samba-packages as possible, basically getting the regular versions and putting in the new versions. 

But as I said, my work isn’t needed any more as the latest RedHat-beta has Samba 4.8 already in it. So I will be pulling in the beta-rpms, rebuild them and install them on my 7.5-system.

**Comment by nkadel** [comment]
The dependencies are why I wrote the structure to use "mock". It builds the dependencies, in order, and pulls the components from that local working repository in the "mock" setups as needed.

**Comment by wiza** [comment]
Thanks, but once I heard it'll be on 7.6, I probably wont have time before that to play with this anyway :)

**Comment by nkadel** [comment]
According to RHEL, their update will be samba-4.8.3. Also, from experience it will not include the actual domain controller packages, but empty stubs called “samba-dc” and the like. Not that i’m objecting to an updates: but the lack of a working samba-dc makes samba much less useful to me.

**Comment by rippiedoos** [comment]
For me it is the TimeMachine support in 4.8 and the file sharing.  But if you use 4.8 with the DC, the use case for 4.9 is even better I can imagine. So if you have to recompile anyway, why not 4.9, as you are already doing. Great effort by the way, this set of packages, but not for me at the moment. I have no use for a DC but others might.

**Comment by nkadel** [comment]
And.... I got tags working for 4.9.1., Wound up resyncing the samba-srpm bundle from the rawhide release, and restoring things that Fedora had discarded, such as the "with_python3" option since /usr/bin/python3 python3 is not directly supported on RHEL 7. But it passes my casual smoke tests.
